-- MySQL Script generated by MySQL Workbench
-- Fri Jun 16 15:01:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema isands_task
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema isands_task
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `isands_task` DEFAULT CHARACTER SET utf8 ;
USE `isands_task` ;

-- -----------------------------------------------------
-- Table `isands_task`.`ElectroType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isands_task`.`ElectroType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isands_task`.`PositionType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isands_task`.`PositionType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isands_task`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isands_task`.`Employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(100) NOT NULL,
  `firstname` VARCHAR(100) NOT NULL,
  `patronymic` VARCHAR(100) NOT NULL,
  `birthday` DATE NOT NULL,
  `PositionType_id` INT NOT NULL,
  `gender` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Employee_PositionType1_idx` (`PositionType_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_PositionType1`
    FOREIGN KEY (`PositionType_id`)
    REFERENCES `isands_task`.`PositionType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isands_task`.`PurchaseType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isands_task`.`PurchaseType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isands_task`.`ElectroEmployee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isands_task`.`ElectroEmployee` (
  `Employee_id` INT NOT NULL,
  `ElectroType_id` INT NOT NULL,
  PRIMARY KEY (`Employee_id`, `ElectroType_id`),
  INDEX `fk_ElectroEmployee_ElectroType_idx` (`ElectroType_id` ASC) VISIBLE,
  INDEX `fk_ElectroEmployee_Employee1_idx` (`Employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_ElectroEmployee_ElectroType`
    FOREIGN KEY (`ElectroType_id`)
    REFERENCES `isands_task`.`ElectroType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ElectroEmployee_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `isands_task`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isands_task`.`Electronics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isands_task`.`Electronics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `ElectroType_id` INT NOT NULL,
  `price` INT NOT NULL,
  `count` INT NOT NULL,
  `inStock` TINYINT NOT NULL,
  `archive` TINYINT NOT NULL,
  `description` VARCHAR(5000) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Electronics_ElectroType1_idx` (`ElectroType_id` ASC) VISIBLE,
  CONSTRAINT `fk_Electronics_ElectroType1`
    FOREIGN KEY (`ElectroType_id`)
    REFERENCES `isands_task`.`ElectroType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isands_task`.`Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isands_task`.`Purchase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Electronics_id` INT NOT NULL,
  `Employee_id` INT NOT NULL,
  `purchaseDate` DATE NOT NULL,
  `PurchaseType_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Purchase_PurchaseType1_idx` (`PurchaseType_id` ASC) VISIBLE,
  INDEX `fk_Purchase_Electronics1_idx` (`Electronics_id` ASC) VISIBLE,
  INDEX `fk_Purchase_Employee1_idx` (`Employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Purchase_PurchaseType1`
    FOREIGN KEY (`PurchaseType_id`)
    REFERENCES `isands_task`.`PurchaseType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Electronics1`
    FOREIGN KEY (`Electronics_id`)
    REFERENCES `isands_task`.`Electronics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `isands_task`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
