/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.isands.service.builder.model.impl;

import com.isands.service.builder.model.Purchase;
import com.isands.service.builder.model.PurchaseModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Purchase service. Represents a row in the &quot;isands_Purchase&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PurchaseModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PurchaseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PurchaseImpl
 * @generated
 */
public class PurchaseModelImpl
	extends BaseModelImpl<Purchase> implements PurchaseModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a purchase model instance should use the <code>Purchase</code> interface instead.
	 */
	public static final String TABLE_NAME = "isands_Purchase";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"purchaseId", Types.BIGINT},
		{"electronicsId", Types.BIGINT}, {"employeeId", Types.BIGINT},
		{"purchaseDate", Types.TIMESTAMP}, {"count", Types.INTEGER},
		{"companyId", Types.BIGINT}, {"purchaseTypeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("purchaseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("electronicsId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("purchaseDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("count", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("purchaseTypeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table isands_Purchase (mvccVersion LONG default 0 not null,purchaseId LONG not null primary key,electronicsId LONG,employeeId LONG,purchaseDate DATE null,count INTEGER,companyId LONG,purchaseTypeId LONG)";

	public static final String TABLE_SQL_DROP = "drop table isands_Purchase";

	public static final String ORDER_BY_JPQL =
		" ORDER BY purchase.purchaseDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY isands_Purchase.purchaseDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ELECTRONICSID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PURCHASEDATE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PurchaseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _purchaseId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPurchaseId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _purchaseId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Purchase.class;
	}

	@Override
	public String getModelClassName() {
		return Purchase.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Purchase, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Purchase, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Purchase, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Purchase)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Purchase, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Purchase, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Purchase)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Purchase, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Purchase, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Purchase, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<Purchase, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Purchase, Object>>();

		attributeGetterFunctions.put("mvccVersion", Purchase::getMvccVersion);
		attributeGetterFunctions.put("purchaseId", Purchase::getPurchaseId);
		attributeGetterFunctions.put(
			"electronicsId", Purchase::getElectronicsId);
		attributeGetterFunctions.put("employeeId", Purchase::getEmployeeId);
		attributeGetterFunctions.put("purchaseDate", Purchase::getPurchaseDate);
		attributeGetterFunctions.put("count", Purchase::getCount);
		attributeGetterFunctions.put("companyId", Purchase::getCompanyId);
		attributeGetterFunctions.put(
			"purchaseTypeId", Purchase::getPurchaseTypeId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<Purchase, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<Purchase, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Purchase, ?>>();

		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<Purchase, Long>)Purchase::setMvccVersion);
		attributeSetterBiConsumers.put(
			"purchaseId", (BiConsumer<Purchase, Long>)Purchase::setPurchaseId);
		attributeSetterBiConsumers.put(
			"electronicsId",
			(BiConsumer<Purchase, Long>)Purchase::setElectronicsId);
		attributeSetterBiConsumers.put(
			"employeeId", (BiConsumer<Purchase, Long>)Purchase::setEmployeeId);
		attributeSetterBiConsumers.put(
			"purchaseDate",
			(BiConsumer<Purchase, Date>)Purchase::setPurchaseDate);
		attributeSetterBiConsumers.put(
			"count", (BiConsumer<Purchase, Integer>)Purchase::setCount);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Purchase, Long>)Purchase::setCompanyId);
		attributeSetterBiConsumers.put(
			"purchaseTypeId",
			(BiConsumer<Purchase, Long>)Purchase::setPurchaseTypeId);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getPurchaseId() {
		return _purchaseId;
	}

	@Override
	public void setPurchaseId(long purchaseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_purchaseId = purchaseId;
	}

	@Override
	public long getElectronicsId() {
		return _electronicsId;
	}

	@Override
	public void setElectronicsId(long electronicsId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_electronicsId = electronicsId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalElectronicsId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("electronicsId"));
	}

	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEmployeeId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("employeeId"));
	}

	@Override
	public Date getPurchaseDate() {
		return _purchaseDate;
	}

	@Override
	public void setPurchaseDate(Date purchaseDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_purchaseDate = purchaseDate;
	}

	@Override
	public int getCount() {
		return _count;
	}

	@Override
	public void setCount(int count) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_count = count;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getPurchaseTypeId() {
		return _purchaseTypeId;
	}

	@Override
	public void setPurchaseTypeId(long purchaseTypeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_purchaseTypeId = purchaseTypeId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Purchase.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Purchase toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Purchase>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PurchaseImpl purchaseImpl = new PurchaseImpl();

		purchaseImpl.setMvccVersion(getMvccVersion());
		purchaseImpl.setPurchaseId(getPurchaseId());
		purchaseImpl.setElectronicsId(getElectronicsId());
		purchaseImpl.setEmployeeId(getEmployeeId());
		purchaseImpl.setPurchaseDate(getPurchaseDate());
		purchaseImpl.setCount(getCount());
		purchaseImpl.setCompanyId(getCompanyId());
		purchaseImpl.setPurchaseTypeId(getPurchaseTypeId());

		purchaseImpl.resetOriginalValues();

		return purchaseImpl;
	}

	@Override
	public int compareTo(Purchase purchase) {
		int value = 0;

		value = DateUtil.compareTo(
			getPurchaseDate(), purchase.getPurchaseDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Purchase)) {
			return false;
		}

		Purchase purchase = (Purchase)object;

		long primaryKey = purchase.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Purchase> toCacheModel() {
		PurchaseCacheModel purchaseCacheModel = new PurchaseCacheModel();

		purchaseCacheModel.mvccVersion = getMvccVersion();

		purchaseCacheModel.purchaseId = getPurchaseId();

		purchaseCacheModel.electronicsId = getElectronicsId();

		purchaseCacheModel.employeeId = getEmployeeId();

		Date purchaseDate = getPurchaseDate();

		if (purchaseDate != null) {
			purchaseCacheModel.purchaseDate = purchaseDate.getTime();
		}
		else {
			purchaseCacheModel.purchaseDate = Long.MIN_VALUE;
		}

		purchaseCacheModel.count = getCount();

		purchaseCacheModel.companyId = getCompanyId();

		purchaseCacheModel.purchaseTypeId = getPurchaseTypeId();

		return purchaseCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Purchase, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Purchase, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Purchase, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Purchase)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Purchase, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Purchase, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Purchase, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Purchase)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Purchase>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Purchase.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _purchaseId;
	private long _electronicsId;
	private long _employeeId;
	private Date _purchaseDate;
	private int _count;
	private long _companyId;
	private long _purchaseTypeId;

	public <T> T getColumnValue(String columnName) {
		Function<Purchase, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Purchase)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("purchaseId", _purchaseId);
		_columnOriginalValues.put("electronicsId", _electronicsId);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("purchaseDate", _purchaseDate);
		_columnOriginalValues.put("count", _count);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("purchaseTypeId", _purchaseTypeId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("purchaseId", 2L);

		columnBitmasks.put("electronicsId", 4L);

		columnBitmasks.put("employeeId", 8L);

		columnBitmasks.put("purchaseDate", 16L);

		columnBitmasks.put("count", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("purchaseTypeId", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Purchase _escapedModel;

}