/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.isands.service.builder.model;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ElectroEmployee service. Represents a row in the &quot;isands_ElectroEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.isands.service.builder.model.impl.ElectroEmployeeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.isands.service.builder.model.impl.ElectroEmployeeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ElectroEmployee
 * @generated
 */
@ProviderType
public interface ElectroEmployeeModel
	extends BaseModel<ElectroEmployee>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a electro employee model instance should use the {@link ElectroEmployee} interface instead.
	 */

	/**
	 * Returns the primary key of this electro employee.
	 *
	 * @return the primary key of this electro employee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this electro employee.
	 *
	 * @param primaryKey the primary key of this electro employee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this electro employee.
	 *
	 * @return the mvcc version of this electro employee
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this electro employee.
	 *
	 * @param mvccVersion the mvcc version of this electro employee
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ID of this electro employee.
	 *
	 * @return the ID of this electro employee
	 */
	public long getId();

	/**
	 * Sets the ID of this electro employee.
	 *
	 * @param id the ID of this electro employee
	 */
	public void setId(long id);

	/**
	 * Returns the electro type ID of this electro employee.
	 *
	 * @return the electro type ID of this electro employee
	 */
	public long getElectroTypeId();

	/**
	 * Sets the electro type ID of this electro employee.
	 *
	 * @param ElectroTypeId the electro type ID of this electro employee
	 */
	public void setElectroTypeId(long ElectroTypeId);

	/**
	 * Returns the employee ID of this electro employee.
	 *
	 * @return the employee ID of this electro employee
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this electro employee.
	 *
	 * @param employeeId the employee ID of this electro employee
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the company ID of this electro employee.
	 *
	 * @return the company ID of this electro employee
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this electro employee.
	 *
	 * @param companyId the company ID of this electro employee
	 */
	@Override
	public void setCompanyId(long companyId);

}