/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.isands.service.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PositionType service. Represents a row in the &quot;isands_PositionType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.isands.service.builder.model.impl.PositionTypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.isands.service.builder.model.impl.PositionTypeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PositionType
 * @generated
 */
@ProviderType
public interface PositionTypeModel
	extends BaseModel<PositionType>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a position type model instance should use the {@link PositionType} interface instead.
	 */

	/**
	 * Returns the primary key of this position type.
	 *
	 * @return the primary key of this position type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this position type.
	 *
	 * @param primaryKey the primary key of this position type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this position type.
	 *
	 * @return the mvcc version of this position type
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this position type.
	 *
	 * @param mvccVersion the mvcc version of this position type
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the position type ID of this position type.
	 *
	 * @return the position type ID of this position type
	 */
	public long getPositionTypeId();

	/**
	 * Sets the position type ID of this position type.
	 *
	 * @param positionTypeId the position type ID of this position type
	 */
	public void setPositionTypeId(long positionTypeId);

	/**
	 * Returns the name of this position type.
	 *
	 * @return the name of this position type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this position type.
	 *
	 * @param name the name of this position type
	 */
	public void setName(String name);

	/**
	 * Returns the company ID of this position type.
	 *
	 * @return the company ID of this position type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this position type.
	 *
	 * @param companyId the company ID of this position type
	 */
	@Override
	public void setCompanyId(long companyId);

}